name: Mobile-Wallet CI[Master/Dev]

on:
  pull_request:
  push:
    branches:
      - 'dev'
      - 'master'
      - 'payment_hub'

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

        # Set up JDK
      - name: Set Up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

        # Update Gradle Permission
      - name: Change gradlew Permission
        run: chmod +x gradlew

        # Build App
      - name: Build with Gradle
        run: ./gradlew assembleDebug --stacktrace

        # Upload Built APK
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2.2.0
        with:
          name: mobile-wallet
          path: mifospay/build/outputs/apk/debug/

  lintCheck:
    name: StaticAnalysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Static Analysis[Core]
        run: ./gradlew core:lint

      - name: Upload Static Analysis Report For Core Module
        uses: actions/upload-artifact@v2.2.0
        with:
          name: Static Analysis Report[Core]
          path: core/build/reports/

      - uses: actions/checkout@v2
      - name: Static Analysis[Mifospay]
        run: ./gradlew mifospay:lint

      - name: Upload Static Analysis Report For MifosPay Module
        uses: actions/upload-artifact@v2.2.0
        with:
          name: Static Analysis Report[Mifospay]
          path: mifospay/build/reports/

      - uses: actions/checkout@v2
      - name: Gradlew Check
        run: ./gradlew pmd
