name: CI Check for Mobile-Wallet
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

      # Set up JDK
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

      # Update Gradle permission
    - name: Change gradlew Permission
      run: chmod +x gradlew

      # Build APK
    - name: Generate APK
      run: ./gradlew assembleDebug --stacktrace

      # Upload Build Artifact
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2.2.0
      with:
        name: app
        path: mifospay/build/outputs/apk/debug/
