name: PullRequest Flow [CI]

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
#      - name: Lint check
#        run: ./gradlew lint
      - name: Go Root
        run: chmod +x ./gradlew  # to eliminate root user errors
      - name: Build with Gradle
        run: ./gradlew assembleDebug
      - name: Upload app APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/